ASSUME CS:CODE, SS:STACK

STACK SEGMENT
	DB 128 DUP(0)
STACK ENDS

CODE SEGMENT
START:
	MOV AX, STACK
	MOV SS, AX
	MOV SP, 128
	
	CALL COPY_BOOT
	
	; 软盘 1 扇区的 前446字节的程序负责将 2 3 扇区的代码复制到 0:7c00H 处
    MOV AX, 4C00H
    INT 21H      

; 将 FIRST_SECTOR 的内容复制到软盘 0 面 0 道 1 扇区
COPY_BOOT:
	JMP FAR PTR COPY_BOOT_S 
	FIRST_SECTOR DB 510 DUP(0)
                 DB 055H, 0AAH 
	OTHER_SECTOR DB 2 * 512 DUP(0) ; 3个扇区
COPY_BOOT_S:
	PUSH ES
	PUSH DI
	PUSH DS
	PUSH SI
	PUSH AX
	PUSH BX
	PUSH DX
	
	MOV AX, CS
	MOV ES, AX
	LEA DI, CS:[FIRST_SECTOR]
	
	MOV AX, CS
	MOV DS, AX
	MOV SI, OFFSET BOOT
	
	CLD
	
	MOV CX, OFFSET BOOT_END - OFFSET BOOT
	
	REP MOVSB
	
	MOV AX, CS
	MOV ES, AX
	LEA BX, CS:[FIRST_SECTOR]
	
	MOV AH, 1 ; 写
	MOV AL, 1 ; 写一个
	MOV DX, 0 ; 1 扇区
	CALL RW_FLOPPY
	
	MOV AX, CS
	MOV ES, AX
	LEA DI, CS:[OTHER_SECTOR]
	
	MOV AX, CS
	MOV DS, AX
	MOV SI, OFFSET YUANSHEN_START
	
	CLD
	
	MOV CX, OFFSET YUANSHEN_END - OFFSET YUANSHEN_START
	
	REP MOVSB
	
	MOV AX, CS
	MOV ES, AX
	LEA BX, CS:[OTHER_SECTOR]
	
	MOV AH, 1 ; 写
	MOV AL, 3 ; 写一个
	MOV DX, 1 ; 2 扇区
	CALL RW_FLOPPY
	
	POP DX
	POP BX
	POP AX
	POP SI
	POP DS
	POP DI
	POP ES
	RET

; 负责将 2 3 扇区的代码复制到 0:7c00H 处
BOOT:
    JMP SHORT BOOT_S
    CALL_RW DD RW_FLOPPY
BOOT_S:   	
	PUSH AX
	PUSH DX
	PUSH ES
	
	MOV AX, 0
	MOV ES, AX
	MOV BX, 07C00H
	
	MOV AH, 0 ; 读
	MOV AL, 3 ; 一个
	MOV DX, 1 ; 2 扇区
	CALL DWORD PTR CS:[CALL_RW]
	
	POP ES
	POP DX
	POP AX
	RET
	
BOOT_END:
	NOP

YUANSHEN_START:	
SYSTEM_TOOLS:
    JMP SHORT SYSTEM_TOOLS_S
    FUN_TOOL_TABLE DW PRINT_HELLO, INPUT_ERROR, CLEAR_SCREEN, DELAY, GOODBYE
    FUN_TABLE DW RESET, STARTUP, CLOCK, SETCOLCK
SYSTEM_TOOLS_S: 
    PUSH AX
	PUSH BX
    PUSH ES
	
    CALL WORD PTR CS:[FUN_TOOL_TABLE + 4] ; CLEAR_SCREEN 

    CALL WORD PTR CS:[FUN_TOOL_TABLE] ; PRINT_HELLO 
    
    MOV AH, 0
    INT 16H
	
	MOV BX, 0B800H
	MOV ES, BX
	
	MOV ES:[5 * 160 + 2 * 19], AL
	
	MOV AH, 0
    INT 16H
	
    SUB AL, 30H
    
	MOV AL, 2
	
    CMP AL, 5H
    JE SYSTEM_TOOLS_O
    CMP AL, 1H
    JB HANDLE_ERROR
    CMP AL, 4H
    JA HANDLE_ERROR
    
    DEC AL

	SHL AL, 1
	XOR AH, AH
	MOV BX, AX
	
	; CALL WORD PTR CS:FUN_TABLE[BX]
	
    JMP SHORT SYSTEM_TOOLS_O
HANDLE_ERROR:
    CALL WORD PTR CS:[FUN_TOOL_TABLE + 4] ; CLEAR_SCREEN 
    CALL WORD PTR CS:[FUN_TOOL_TABLE + 2] ; INPUT_ERROR
    MOV AH, 0
    INT 16H
    JMP SHORT SYSTEM_TOOLS_S 
SYSTEM_TOOLS_O:                               
    CALL WORD PTR CS:[FUN_TOOL_TABLE + 4] ; CLEAR_SCREEN 
    CALL WORD PTR CS:[FUN_TOOL_TABLE + 8] ; GOODBYE    
	
    MOV AH, 0
    INT 16H

	POP ES
	POP BX
    POP AX
    RET

RESET:
	JMP SHORT RESET_S
	RESET_UNIT DW 0, 0FFFFH
RESET_S:
	JMP DWORD PTR CS:[RESET_UNIT]
	RET
	
STARTUP:
	JMP SHORT STARTUP_S
	RW_ADDR DW 0, 7C00H, 0
STARTUP_S:
	CALL DWORD PTR CS:[RW_ADDR + 2]
	RET
	
CLOCK:
	RET
	
SETCOLCK:
	RET
	
PRINT_HELLO:
    JMP SHORT  PRINT_HELLO_S 
    STRING1 DB '1) RETSET PC',0
    STRING2 DB '2) START SYSTEM',0
    STRING3 DB '3) CLOCK',0
    STRING4 DB '4) SET CLOCK',0 
    STRING5 DB '5) EXIT', 0
    STRING6 DB 'PLEASE INTPUT(1-5):',0
    STRING_OFFSET DW STRING1, STRING2, STRING3, STRING4, STRING5, STRING6
    STRING_COUNTS DW 6
PRINT_HELLO_S:
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX

    MOV AX, CS
    MOV DS, AX
    XOR BX, BX
    
    MOV DX, 0000H
    
    MOV AX, CS:[STRING_COUNTS]
    MOV CX, AX   
PRINT_LOOP:
        PUSH CX
        
        MOV SI, CS:STRING_OFFSET[BX]
        MOV CL, 7H
        CALL PRINT_STRING
        ADD BX, 2
        INC DH ; 提一行

        POP CX
    LOOP PRINT_LOOP

PRINT_HELLO_O:
    POP DX
    POP CX
    POP BX
    POP AX
    RET               

; DH 行 DL 列 CL 颜色 DS:SI 字符串位置
PRINT_STRING:
    PUSH AX
    PUSH BX
    PUSH CX
    PUSH DX
    PUSH ES
    PUSH SI
PRINT_STRING_S:
    
    MOV BX, 0B800H
    MOV ES, BX

    MOV AL, 160
    MUL DH
    
    MOV BX, AX
    
    SHL DL, 1
    XOR DH, DH
    
    ADD BX, DX
    
    XCHG CH, CL
PRINT_STRING_LOOP: 
    MOV CL, DS:[SI]
    CMP CL, 0
    JE PRINT_STRING_O
    MOV ES:[BX], CX
    ADD BX, 2
    INC SI
    JMP SHORT PRINT_STRING_LOOP     

PRINT_STRING_O:
    POP SI
    POP ES
    POP DX
    POP CX
    POP BX
    POP AX

    RET

INPUT_ERROR:                                             
    JMP SHORT INPUT_ERROR_S
    ERROR_STRING  DB 'INVAILD INPUT. PLEASE INPUT 1-4', 0
    ERROR_STRING2 DB 'PRESS ANY KEY TO RETURN MENU', 0
INPUT_ERROR_S:
    PUSH AX
    PUSH CX
    PUSH DX
    PUSH DS
    PUSH SI

    MOV AX, CS
    MOV DS, AX
    LEA SI, CS:[ERROR_STRING]
    MOV CL, 4H
    MOV DX, 0000H
    CALL PRINT_STRING
    
    LEA SI, CS:[ERROR_STRING2]
    MOV CL, 4H
    INC DH
    CALL PRINT_STRING
INPUT_ERROR_O:
    POP SI
    POP DS
    POP DX
    POP CX
    POP AX    
    RET    

CLEAR_SCREEN:
    PUSH AX
    PUSH CX
    PUSH ES
    PUSH DI
CLEAR_SCREEN_S:    
    MOV AX, 0B800H
    MOV ES, AX
    XOR DI, DI
    
    MOV AX, 0700H
    
    CLD 
    
    MOV CX, 2000
    
    REP STOSW

    POP DI
    POP ES    
    POP CX
    POP AX
    RET

DELAY:
    PUSH AX
    PUSH DX
DELAY_S:
    MOV AX, 0FFFFH
    MOV DX, 0FFFFH
    CLC
DELAY_LOOP:
    SUB AX, 1H
    SBB DX, 0H
    CMP AX, 0H
    JNE DELAY_LOOP
    CMP DX, 0H
    JNE DELAY_LOOP
DELAY_O:    
    POP DX
    POP AX
    RET

GOODBYE:                                             
    JMP SHORT GOODBYE_S
    GOODBYE_STRING  DB 'GOODBYE!!!', 0
GOODBYE_S:
    PUSH AX
    PUSH CX
    PUSH DX
    PUSH DS
    PUSH SI

    MOV AX, CS
    MOV DS, AX
    LEA SI, CS:[GOODBYE_STRING]
    MOV CL, 4H
    MOV DX, 0000H
    CALL PRINT_STRING
GOODBYE_O:
    POP SI
    POP DS
    POP DX
    POP CX
    POP AX    
    RET

; DX 传递逻辑扇区号 AH 传递读写 AL 传递写数量 ES:BX 存储或读写 
RW_FLOPPY:
	JMP SHORT RW_FLOPPY_S
	DIVISOR1 DW 1440
	DIVISOR2 DW 18
RW_FLOPPY_S:
	PUSH AX
	PUSH CX
	PUSH DX
	
	PUSH AX
	MOV AX, DX
	XOR DX, DX
	DIV CS:[DIVISOR1] ; AX = INT(逻辑扇区/1440) DX = REM(逻辑扇区/1440)
	
	PUSH AX
	
	MOV AX, DX
	XOR DX, DX
	DIV CS:[DIVISOR2] ; AX = INT(REM(逻辑扇区/1440)/18) DX = REM(REM(逻辑扇区/1440)/18)
	
	INC DX
	
	MOV CL, DL
	MOV CH, AL
	
	POP AX
	MOV DH, AL
	MOV DL, 0H
	
	POP AX
	
	CMP AH, 1H
    JA RW_FLOPPY_O
	ADD AH, 2
	INT 13H
	JC RW_FLOPPY_O
RW_FLOPPY_O:	
	POP DX
	POP CX
	POP AX
	RET

YUANSHEN_END:
	NOP
	
CODE ENDS
END START