ASSUME CS:CODESG 

CODESG SEGMENT
  DW 0123H, 0456H, 0789H, 0ABCH, 0DEFH, 0FEDH, 0CBAH, 0987H
START: MOV AX, 0H
       MOV DS, AX
       MOV BX, 0H

       MOV CX, 8H
    S: MOV AX, [BX]
       MOV CS:[BX], AX
       ADD BX, 2H
       LOOP S

       MOV AX, 4C00H
       INT 21H
CODESG ENDS
END START