#include <REGX52.H>
#include "timer0.h"
#include "Delay.h"

#define SPEED 600
#define BASE_DELAY (SPEED / 4)

#define L1 	0
#define L1_ 1
#define L2 	2
#define L2_ 3
#define L3 	4
#define L4 	5
#define L4_ 6
#define L5	7
#define L5_	8
#define L6 	9
#define L6_ 10
#define L7 	11

#define M1 	12
#define M1_ 13
#define M2 	14
#define M2_ 15
#define M3 	16
#define M4 	17
#define M4_ 18
#define M5	19
#define M5_	20
#define M6 	21
#define M6_ 22
#define M7 	23

#define H1 	24
#define H1_ 25
#define H2 	26
#define H2_ 27
#define H3 	28
#define H4 	29
#define H4_ 30
#define H5	31
#define H5_	32
#define H6 	33
#define H6_ 34
#define H7 	35

#define SILENCE 36

// 音符时值宏定义
#define WHOLE_NOTE       16  // 全音符 (16个时间单位)
#define HALF_NOTE        8   // 二分音符
#define QUARTER_NOTE     4   // 四分音符
#define EIGHTH_NOTE      2   // 八分音符
#define SIXTEENTH_NOTE   1   // 十六分音符

// 附点音符宏定义
#define DOTTED_HALF_NOTE     (HALF_NOTE + QUARTER_NOTE)      // 附点二分音符
#define DOTTED_QUARTER_NOTE  (QUARTER_NOTE + EIGHTH_NOTE)    // 附点四分音符

// 三连音宏定义
#define TRIPLET_QUARTER     (QUARTER_NOTE * 2 / 3)  // 四分音符三连音
#define TRIPLET_EIGHTH      (EIGHTH_NOTE * 2 / 3)   // 八分音符三连音

#define SLUR 0x80  // 圆滑线标志
#define END_MARKER 0xFF

#define FIRST_ROW  1
#define SECOND_ROW 2

// D调频率表 (严格遵循原始宏定义结构)
unsigned int code FreqTable[] = {
    // 低音区 (D3 ~ B3)
    63879,   // L1: D3 (293.66Hz)
    63589,   // L1_: D#3 (311.13Hz)
    64118,   // L2: E3 (329.63Hz)
    63786,   // L2_: F3 (349.23Hz)
    64321,   // L3: F#3 (369.99Hz)
    64438,   // L4: G3 (392.00Hz)
    63879,   // L4_: G#3 (415.30Hz)
    64635,   // L5: A3 (440.00Hz)
    63961,   // L5_: A#3 (466.16Hz)
    64792,   // L6: B3 (493.88Hz)
    64382,   // L6_: C4 (523.25Hz) - 跨区
    64491,   // L7: C#4 (554.37Hz) - 跨区
    
    // 中音区 (D4 ~ B4)
    64542,   // M1: D4 (293.66Hz)
    64590,   // M1_: D#4 (311.13Hz)
    64678,   // M2: E4 (329.63Hz)
    64718,   // M2_: F4 (349.23Hz)
    64756,   // M3: F#4 (369.99Hz)
    64792,   // M4: G4 (392.00Hz)
    64826,   // M4_: G#4 (415.30Hz)
    64858,   // M5: A4 (440.00Hz)
    64888,   // M5_: A#4 (466.16Hz)
    64916,   // M6: B4 (493.88Hz)
    64943,   // M6_: C5 (523.25Hz) - 跨区
    64968,   // M7: C#5 (554.37Hz) - 跨区
    
    // 高音区 (D5 ~ B5)
    64992,   // H1: D5 (587.33Hz)
    65015,   // H1_: D#5 (622.25Hz)
    65036,   // H2: E5 (659.26Hz)
    65056,   // H2_: F5 (698.46Hz)
    65075,   // H3: F#5 (739.99Hz)
    65093,   // H4: G5 (783.99Hz)
    65110,   // H4_: G#5 (830.61Hz)
    65126,   // H5: A5 (880.00Hz)
    65141,   // H5_: A#5 (932.33Hz)
    65155,   // H6: B5 (987.77Hz) - 新增
    65168,   // H6_: C6 (1046.50Hz) - 新增
    65181,   // H7: C#6 (1108.73Hz) - 新增
    
    // 休止符
    0        // SILENCE
};

typedef struct
{
    unsigned char noteIndex;  // 音符索引
    unsigned char duration;   // 时值（包含可能的标志位）
} ScaleNote;

code ScaleNote Song[] = {
    //1
	{SILENCE, QUARTER_NOTE},
	{SILENCE, QUARTER_NOTE},
	{SILENCE, QUARTER_NOTE},
	{SILENCE, SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//2
	{M3, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M6,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//3
	{H1,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE | SLUR},
	{M5,SIXTEENTH_NOTE},
	{M5,QUARTER_NOTE},
	{SILENCE, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	
	//4
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	{M1,EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	
	//5
	{M3, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M2, SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	{M1, EIGHTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	
	{M2, QUARTER_NOTE},
	{M1, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M2, SIXTEENTH_NOTE},
	
	//6
	{M3, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE | SLUR},
	{M3, SIXTEENTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M6, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M1, SIXTEENTH_NOTE},

	//7
	{H1,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE | SLUR},
	{M5,SIXTEENTH_NOTE},
	{M5,QUARTER_NOTE},
	{SILENCE,EIGHTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//8
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE | SLUR},
	{H1,SIXTEENTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//9
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1,QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//10
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE + QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	
	//11
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//12
	{H2,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + QUARTER_NOTE},
	{SILENCE,SIXTEENTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	
	//13
	{H3,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE + QUARTER_NOTE},
	{H3,EIGHTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//14
	{H2,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE | SLUR},
	{H3, QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	
	//15
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1, QUARTER_NOTE + QUARTER_NOTE},
	
	//16
	{SILENCE,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//17
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1, QUARTER_NOTE + QUARTER_NOTE},
	//A END

//1
	{SILENCE, QUARTER_NOTE},
	{SILENCE, QUARTER_NOTE},
	{SILENCE, QUARTER_NOTE},
	{SILENCE, SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//2
	{M3, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M6,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//3
	{H1,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE | SLUR},
	{M5,SIXTEENTH_NOTE},
	{M5,QUARTER_NOTE},
	{SILENCE, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	
	//4
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	{M1,EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	
	//5
	{M3, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M2, SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	{M1, EIGHTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	
	{M2, QUARTER_NOTE},
	{M1, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M2, SIXTEENTH_NOTE},
	
	//6
	{M3, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE | SLUR},
	{M3, SIXTEENTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M6, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	
	//7
	{H1,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE | SLUR},
	{M5,SIXTEENTH_NOTE},
	{M5,QUARTER_NOTE},
	{SILENCE,EIGHTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//8
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE | SLUR},
	{H1,SIXTEENTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//9
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1,QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//10
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE + QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	
	//11
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//12
	{H2,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + QUARTER_NOTE},
	{SILENCE,SIXTEENTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	
	//13
	{H3,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE + QUARTER_NOTE},
	{H3,EIGHTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//14
	{H2,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE | SLUR},
	{H3, QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	
	//15
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1, QUARTER_NOTE + QUARTER_NOTE},
	
	//16
	{SILENCE,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//17
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1, QUARTER_NOTE + QUARTER_NOTE},
	//A END

//1
	{SILENCE, QUARTER_NOTE},
	{SILENCE, QUARTER_NOTE},
	{SILENCE, QUARTER_NOTE},
	{SILENCE, SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//2
	{M3, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M6,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//3
	{H1,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE | SLUR},
	{M5,SIXTEENTH_NOTE},
	{M5,QUARTER_NOTE},
	{SILENCE, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	
	//4
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	{M1,EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	
	//5
	{M3, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M2, SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	{M1, EIGHTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	
	{M2, QUARTER_NOTE},
	{M1, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M2, SIXTEENTH_NOTE},
	
	//6
	{M3, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE | SLUR},
	{M3, SIXTEENTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M5, SIXTEENTH_NOTE},
	{M3, SIXTEENTH_NOTE},
	{M6, EIGHTH_NOTE},
	{M5, EIGHTH_NOTE},
	{M3, EIGHTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	{M1, SIXTEENTH_NOTE},
	
	//7
	{H1,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE | SLUR},
	{M5,SIXTEENTH_NOTE},
	{M5,QUARTER_NOTE},
	{SILENCE,EIGHTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	{M1,SIXTEENTH_NOTE},
	
	//8
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE | SLUR},
	{H1,SIXTEENTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//9
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1,QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//10
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE + QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	
	//11
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//12
	{H2,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + QUARTER_NOTE},
	{SILENCE,SIXTEENTH_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	
	//13
	{H3,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE + QUARTER_NOTE},
	{H3,EIGHTH_NOTE},
	{H3,SIXTEENTH_NOTE},
	{H3,SIXTEENTH_NOTE + QUARTER_NOTE},
	
	//14
	{H2,EIGHTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H2,SIXTEENTH_NOTE | SLUR},
	{H3, QUARTER_NOTE},
	{M5,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE + SIXTEENTH_NOTE},
	
	//15
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1, QUARTER_NOTE + QUARTER_NOTE},
	
	//16
	{SILENCE,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//17
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1, QUARTER_NOTE + QUARTER_NOTE},
	//A END
	
	//18 B
	{SILENCE,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//19
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,SIXTEENTH_NOTE},
	{M5,SIXTEENTH_NOTE + EIGHTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M1,QUARTER_NOTE + QUARTER_NOTE},
	
	//20
	{SILENCE,EIGHTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{H1,SIXTEENTH_NOTE},
	{M6,SIXTEENTH_NOTE},
	{H3,EIGHTH_NOTE},
	{H2,EIGHTH_NOTE},
	{H1,QUARTER_NOTE},
	
	//21
	{M2,SIXTEENTH_NOTE},
	{M3,SIXTEENTH_NOTE},
	{M2,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE | SLUR},
	{M6,SIXTEENTH_NOTE| SLUR},
	{M5,SIXTEENTH_NOTE| SLUR},
	{H1,EIGHTH_NOTE| SLUR},
	{H2,SIXTEENTH_NOTE| SLUR},
	{H1,SIXTEENTH_NOTE| SLUR},
	{H3,EIGHTH_NOTE| SLUR},
	{H4,SIXTEENTH_NOTE| SLUR},
	{H3,SIXTEENTH_NOTE| SLUR},
	
	//22
	{H5,QUARTER_NOTE + QUARTER_NOTE},
	{SILENCE,EIGHTH_NOTE},
	{M5,EIGHTH_NOTE},
	{H3,EIGHTH_NOTE},
	{H5,SIXTEENTH_NOTE},
	
	//23
	{H1, QUARTER_NOTE + QUARTER_NOTE + QUARTER_NOTE + QUARTER_NOTE},
	// 结束标记
    {END_MARKER, 0} // 315
};

sbit beep = P2^5;
unsigned char KeyNum = 0;
unsigned char FreqSelect = 0;

void main()
{
	unsigned int currentIndex = 0; // 当前音符索引
	ScaleNote * currentNote = Song;
	
	Timer0_Init();
	while(1)
	{
		if(currentNote->noteIndex != END_MARKER)
		{
			if(currentNote->noteIndex != SILENCE) {
				FreqSelect = currentNote->noteIndex;
                TR0 = 1; // 启动定时器
            }
            
            // 音符持续时间
            Delay(BASE_DELAY  * (currentNote->duration & 0x7F));
            
            // 处理圆滑线标志
            if(!(currentNote->duration & SLUR)) {
                TR0 = 0; // 停止定时器
                beep = 0; // 确保蜂鸣器关闭
                Delay(5); // 音符间停顿
				TR0 = 1;
            }
			
			currentNote++;
		}else
		{	
			TR0 = 0;
			beep = 0;
		}
	}
}

void Timer0_Rountine() interrupt 1
{
	if(FreqTable[FreqSelect])
	{
		TH0 = FreqTable[FreqSelect]  / 256;
		TL0 = FreqTable[FreqSelect] % 256;
	
		beep = !beep;
	}
}
